AllCops:
  Exclude:
    - spec/**/*.rb
    - leo.gemspec
Documentation:
  Enabled: true

Metrics/AbcSize:
  Max: 17

ClassAndModuleChildren:
  EnforcedStyle: nested
  SupportedStyles:
    - nested
    - compact

MethodLength:
  CountComments: false  # count full line comments?
  Max: 16

LineLength:
  Max: 120
