---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install: 'printf "y" | rvm @global do gem uninstall bundler; gem install bundler -v "~> 1.17.2"'
notifications:
  email:
on_success: never
script:
- bundle exec rake
